name: "ADR: Architecture Decision Records"
description: なんか設計の意思決定残すやつ
labels: ["adr"]
body:
  - type: markdown
    attributes:
      value: |
        タイトルは短い名詞で書きましょう。英単語にしてください。例: "Use PostgreSQL for database"
        こちらに準拠して書きましょう [Michael Nygardのフォーマット](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions)

  - type: textarea
    id: context
    attributes:
      label: Context
      description: 概要、技術的、歴史的背景について ※ #### から使ってください
    validations:
      required: true

  - type: textarea
    id: decision
    attributes:
      label: Decision
      description: 決定事項を書きます ※ #### から使ってください
    validations:
      required: false

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Proposed
        - Approved
        - Deprecated
        - Superseded
      default: 0
    validations:
      required: true

  - type: textarea
    id: consequences
    attributes:
      label: Consequences
      description: 決定を適用した後の状況について書きます ※ #### から使ってください
    validations:
      required: false
